#!/usr/bin/env bash
# Start the CAD Viewer the way the shipped skill tells a user to, and check it answers.
#
# Every other check asks whether the distribution is correctly ASSEMBLED. bundle.sh --check
# compares generated bytes, check-builds.sh inspects the layout. None of them RUN it.
# `npm start` was declared in the runtime's package.json, shipped without its launcher,
# and stayed broken from 0.4.0 to 0.4.18 because no test ever executed the one command the
# skill documents.
#
# The command below is that command: `cadgen viewer --host 127.0.0.1 --json`, spelled
# `python -m cadgen.viewer` so the interpreter is explicit. Keep it identical to the one
# in skills/cad-viewer/SKILL.md; if the doc changes, this changes with it. Launching is
# unconditional (the server rolls to a free port and prints the real URL/port), so this
# script chooses no port: it reads the port from the --json line, exactly as an agent
# does. It serves the client the WHEEL ships -- cadgen/_runtime/viewer, written by
# scripts/bundle/bundle.sh -- pinned through CADGEN_VIEWER_DIST so a checkout's own
# apps/viewer/dist cannot stand in for it. Run bundle.sh first, exactly as test.yml does.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

HOST="127.0.0.1"
# VIEWER_RUNTIME_DIR points the smoke test at a client bundled somewhere else
# (CADGEN_RUNTIME_CHECK_DIR-style scratch builds). CI uses the default.
RUNTIME="${VIEWER_RUNTIME_DIR:-$REPO_ROOT/packages/cadgen/src/cadgen/_runtime/viewer}"

echo "==> CAD Viewer launch smoke test (\$PYTHON -m cadgen.viewer)"

# The built client has to be IN the wheel's runtime: its absence is the exact regression
# this guards, and it surfaces as a served page that is 404 rather than as a bad server.
if [ ! -f "$RUNTIME/index.html" ]; then
  echo "FAIL: no bundled CAD Viewer client at $RUNTIME (index.html missing)" >&2
  echo "      Run scripts/bundle/bundle.sh first (test.yml bundles before this step)." >&2
  exit 1
fi
export CADGEN_VIEWER_DIST="$RUNTIME"

log="$(mktemp)"
serve_root="$(mktemp -d)"
# This is the interpreter that plays the role of "the one that installed
# skills/cad-viewer/requirements.txt" -- the server is a module of that cadgen.
#
# Resolution FALLS BACK instead of demanding a repo venv, because there are two
# venv-less callers and both are ordinary:
#
#   * GitHub Actions. .github/actions/setup-deps uses actions/setup-python and
#     installs requirements-dev.txt into the interpreter on PATH; no .venv is
#     ever created. Hard-requiring $REPO_ROOT/.venv/bin/python made this step
#     fail before it started anything, on every pull request.
#   * A lightweight worktree. CONTRIBUTING's recipe deliberately does not copy
#     .venv, so a developer running this by hand hit the identical wall.
#
# Setting VIEWER_PYTHON in test.yml would have fixed only the first. The
# fallback fixes both, and uses the same order scripts/test/common.sh already
# uses for every other Python runner in this repo, so "which interpreter do the
# tests use" has one answer.
#
# The first candidate that can import cadgen wins, and cadgen is REQUIRED: the
# end-to-end import below is most of what this script proves, so a machine that
# cannot run it should say so here in one line rather than 60 seconds later
# inside a POST that returns ok:false. An explicit VIEWER_PYTHON is never
# second-guessed — it is used, or the script fails naming it.
pick_interpreter() {
  local candidates=()
  if [ -n "${VIEWER_PYTHON:-}" ]; then
    candidates=("$VIEWER_PYTHON")
  else
    candidates=(
      "$REPO_ROOT/.venv/bin/python"
      "$REPO_ROOT/.venv/Scripts/python.exe"
      python3
      python
    )
  fi

  local candidate resolved
  FOUND_INTERPRETER=""
  for candidate in "${candidates[@]}"; do
    resolved="$(command -v "$candidate" 2>/dev/null || true)"
    [ -n "$resolved" ] && [ -x "$resolved" ] || continue
    [ -n "$FOUND_INTERPRETER" ] || FOUND_INTERPRETER="$resolved"
    if "$resolved" -c 'import importlib.util, sys; sys.exit(0 if importlib.util.find_spec("cadgen") else 1)' \
        >/dev/null 2>&1; then
      PYTHON="$resolved"
      return 0
    fi
  done
  return 1
}

if ! pick_interpreter; then
  if [ -n "${VIEWER_PYTHON:-}" ]; then
    echo "FAIL: VIEWER_PYTHON=$VIEWER_PYTHON cannot run, or cannot import cadgen." >&2
  elif [ -z "$FOUND_INTERPRETER" ]; then
    echo "FAIL: no Python interpreter found (tried the repo venv, python3, and python)." >&2
    echo "      Set VIEWER_PYTHON to the one that installed requirements-dev.txt." >&2
    exit 1
  else
    echo "FAIL: cadgen is not importable from $FOUND_INTERPRETER." >&2
  fi
  echo "      This test imports a real STEP end to end, so the launching interpreter" >&2
  echo "      needs cadgen: pip install -r requirements-dev.txt, or set VIEWER_PYTHON." >&2
  exit 1
fi
echo "    interpreter: $PYTHON"
# Cold: a smoke test spawns no build daemon.
export CADGEN_DAEMON=0
unset CADGEN_BROKER CADGEN_BROKER_KEY CADGEN_BROKER_STATS CADGEN_ROOT_ID
# Isolated store: content keying would otherwise resolve the fixture against
# the developer's real cache and skip the import this smoke test exists to run.
export CADGEN_CACHE_DIR="$(mktemp -d)"
# The instance registry lives in the process temp directory, outside the store.
# Keep reuse/list/stop checks independent of other viewers on this machine.
registry_tmp="$("$PYTHON" -c 'import tempfile; print(tempfile.mkdtemp(prefix="cv-"))')"
export TMPDIR="$registry_tmp" TEMP="$registry_tmp" TMP="$registry_tmp"
export CADGEN_DAEMON_STATE_DIR="$registry_tmp/daemon"
# The launcher has no directory flag: the cwd IS the served directory, so the
# launch cd's there first — exactly as SKILL.md instructs. `exec` makes the
# subshell BECOME the python process, so $! is the server's pid.
(cd "$serve_root" && exec "$PYTHON" -m cadgen.viewer --host "$HOST" --json) > "$log" 2>&1 &
server_pid=$!
disown "$server_pid" 2>/dev/null || true

cleanup() {
  kill "$server_pid" 2>/dev/null || true
  wait "$server_pid" 2>/dev/null || true
  rm -rf "$serve_root" "$CADGEN_CACHE_DIR" "$registry_tmp"
  rm -f "$log"
}
trap cleanup EXIT

# The port is an OUTPUT of launch: read it from the {url,port,action} JSON line.
PORT=""
for _ in $(seq 1 30); do
  PORT="$(sed -n 's/^{.*"port":\([0-9]*\).*}$/\1/p' "$log" | tail -1)"
  [ -n "$PORT" ] && break
  if ! kill -0 "$server_pid" 2>/dev/null; then
    echo "FAIL: the server exited before printing its contract" >&2
    sed 's/^/    /' "$log" >&2
    exit 1
  fi
  sleep 1
done
if [ -z "$PORT" ]; then
  echo "FAIL: no {url,port,action} JSON line appeared" >&2
  sed 's/^/    /' "$log" >&2
  exit 1
fi

# The launcher writes the {url,port,action} line only after the socket is bound and
# listening with the app attached (pinned by tests/python/packages/cadgen/viewer/test_launcher.py
# AnnounceIsConnectable: first request, no retry, 1s budget), so the FIRST request after
# reading it answers 200. The two extra attempts are slack for a starved CI runner, not
# cover for the launcher — a miss is printed so it cannot pass silently, and a launcher
# that needed the retry fails the unit pin first.
status=""
attempt=0
for _ in $(seq 1 3); do
  attempt=$((attempt + 1))
  status="$(curl -s -o /dev/null -m 3 -w '%{http_code}' "http://$HOST:$PORT/" || true)"
  [ "$status" = "200" ] && break
  echo "    warning: request $attempt after the announce returned ${status:-none}; retrying" >&2
  sleep 1
done
if [ "$status" != "200" ]; then
  echo "FAIL: no 200 from http://$HOST:$PORT/ within $attempt requests (last status: ${status:-none})" >&2
  sed 's/^/    /' "$log" >&2
  exit 1
fi

# The front end alone is not proof: the server serves a prebuilt bundle, so a live page with
# a dead CAD API still looks fine in a browser until the first model load.
api="$(curl -s -o /dev/null -m 3 -w '%{http_code}' "http://$HOST:$PORT/__cad/server" || true)"
if [ "$api" != "200" ]; then
  echo "FAIL: the page served but /__cad/server returned ${api:-none}" >&2
  sed 's/^/    /' "$log" >&2
  exit 1
fi

# Launch idempotence: relaunching from the same directory at the same version must
# REUSE the running viewer (same port, action:"reused"), not spawn a second instance.
reuse_json="$(cd "$serve_root" && "$PYTHON" -m cadgen.viewer --host "$HOST" --json | grep '^{' | tail -1)"
if ! printf '%s' "$reuse_json" | grep -q '"action":"reused"'; then
  echo "FAIL: relaunching the same root did not reuse the running viewer: $reuse_json" >&2
  exit 1
fi
if ! printf '%s' "$reuse_json" | grep -q "\"port\":$PORT"; then
  echo "FAIL: reuse reported a different port than the running viewer: $reuse_json" >&2
  exit 1
fi

# End-to-end display FROM THE BUNDLE: a raw STEP in the served root goes
# not-compiled -> POST (cadgen's compile entry point, a job in the pool)
# -> compiled geometry -> a real browser load that derives and fetches its
# display surface. Its small STEP fixture belongs to this test rather than the
# repository's shared model workspace. Geometry completion and display readiness
# are separate contracts: the artifact endpoint must stay "compiled" after the
# geometry tree lands, while
# the bundled client drives missing SURF work through /__cad/surfaces.
FIXTURE="$REPO_ROOT/tests/fixtures/cad/import-smoke.step"
if ! head -1 "$FIXTURE" | grep -q "ISO-10303-21"; then
  echo "FAIL: import fixture is not STEP text: $FIXTURE" >&2
  exit 1
fi
cp "$FIXTURE" "$serve_root/smoke.step"
step_url="http://$HOST:$PORT/__cad/artifact?file=smoke.step"
status_json="$(curl -s -m 10 "$step_url")"
if ! printf '%s' "$status_json" | grep -q '"not-compiled"'; then
  echo "FAIL: raw STEP did not report not-compiled: $status_json" >&2
  exit 1
fi
if ! printf '%s' "$status_json" | grep -q '"compile":true'; then
  echo "FAIL: raw STEP status did not offer the compile: $status_json" >&2
  exit 1
fi
# The compile pays one cold interpreter + OCP start; give it a real timeout.
build_json="$(curl -s -m 120 -X POST -H 'x-cadgen-viewer: 1' "$step_url")"
if ! printf '%s' "$build_json" | grep -q '"ok":true'; then
  echo "FAIL: the compile did not succeed: $build_json" >&2
  exit 1
fi
# The tree lands in the (isolated) store, keyed by the document's bytes.
if ! ls "$CADGEN_CACHE_DIR"/index/document/* > /dev/null 2>&1; then
  echo "FAIL: compile reported ok but the store indexes no document" >&2
  exit 1
fi
status_json="$(curl -s -m 10 "$step_url")"
if ! printf '%s' "$status_json" | grep -q '"state":"compiled"'; then
  echo "FAIL: compiled STEP did not settle compiled: $status_json" >&2
  exit 1
fi
if ! printf '%s' "$status_json" | grep -q '"ref":"/__cad/store?'; then
  echo "FAIL: compiled STEP did not publish its immutable store ref: $status_json" >&2
  exit 1
fi

# Loading the page is load-bearing. Merely accepting the new compiled state
# would let this smoke pass with a dead display path: a cold isolated store has
# no SURF or TESS entries, so the bundled client must request exact surface
# derivation, fetch the pinned SURF bytes, tessellate them, and clear its loading
# overlay. CI installs Playwright's Chromium with requirements-dev.txt.
"$PYTHON" - "http://$HOST:$PORT/?file=smoke.step" "$(cat "$REPO_ROOT/VERSION")" <<'PY'
import sys
import time
from urllib.parse import parse_qs, urlparse

from playwright.sync_api import sync_playwright

url = sys.argv[1]
responses = []
page_errors = []
surface_payload = None
surface_fetches = set()

with sync_playwright() as playwright:
    browser = playwright.chromium.launch(
        headless=True,
        args=["--use-angle=swiftshader", "--enable-unsafe-swiftshader", "--ignore-gpu-blocklist"],
    )
    try:
        page = browser.new_page(viewport={"width": 1000, "height": 720})
        # The startup update check must not depend on GitHub or its rate limit.
        page.route(
            "https://api.github.com/repos/earthtojake/text-to-cad/releases/latest",
            lambda route: route.fulfill(json={"tag_name": f"v{sys.argv[2]}"}),
        )
        page.on("response", lambda response: responses.append(response))
        page.on("pageerror", lambda error: page_errors.append(str(error)))
        page.goto(url, wait_until="domcontentloaded", timeout=30_000)

        seen = 0
        deadline = time.monotonic() + 120
        while time.monotonic() < deadline:
            page.wait_for_timeout(100)
            current = responses[seen:]
            seen = len(responses)
            for response in current:
                request = response.request
                parsed = urlparse(response.url)
                if parsed.path == "/__cad/surfaces" and request.method == "POST" and response.ok:
                    payload = response.json()
                    components = payload.get("components") if isinstance(payload, dict) else None
                    if components and all(row.get("state") == "ready" for row in components.values()):
                        surface_payload = payload
                elif parsed.path == "/__cad/store" and response.ok:
                    query = parse_qs(parsed.query)
                    if query.get("tree") and query.get("surfaceInput") and query.get("object"):
                        surface_fetches.add(response.url)

            overlay_gone = page.locator(".cad-loading-overlay").count() == 0
            if surface_payload and surface_fetches and overlay_gone:
                break

        if page_errors:
            raise RuntimeError("browser page error: " + " | ".join(page_errors))
        if not surface_payload:
            raise RuntimeError("bundled client did not complete a cold /__cad/surfaces request")
        rows = surface_payload["components"]
        missing = [
            cid for cid, row in rows.items()
            if not any(fetch.endswith(row["url"]) for fetch in surface_fetches)
        ]
        if missing:
            raise RuntimeError("bundled client did not fetch pinned SURF bytes for: " + ", ".join(missing))
        if page.locator(".cad-loading-overlay").count():
            raise RuntimeError("bundled client did not finish tessellating the display surface")
        canvases = page.locator("canvas")
        if not canvases.count() or not any(canvases.nth(index).is_visible() for index in range(canvases.count())):
            raise RuntimeError("bundled client completed surface work without a visible canvas")
        alerts = [text.strip() for text in page.locator('[role="alert"]').all_text_contents() if text.strip()]
        if alerts:
            raise RuntimeError("bundled client reported an alert: " + " | ".join(alerts))
        print(f"    bundled client displayed {len(rows)} cold-derived surface component(s)")
    finally:
        browser.close()
PY

# The instance-manager side of the same entrypoint: list must show this server,
# stop must end it.
if ! "$PYTHON" -m cadgen.viewer list | grep -q "port $PORT"; then
  echo "FAIL: 'cadgen viewer list' did not report the running viewer" >&2
  exit 1
fi
if ! "$PYTHON" -m cadgen.viewer stop --port "$PORT" | grep -q "Stopped CAD Viewer"; then
  echo "FAIL: 'cadgen viewer stop --port $PORT' did not stop the viewer" >&2
  exit 1
fi

echo "    served / and /__cad/server on rolled port $PORT; cadgen step compile + bundled display e2e OK; reuse/list/stop OK"
echo "==> CAD Viewer launch smoke test passed"
