"""SOURCE OF TRUTH: TEXT-TO-CAD precision-repair pipeline.

Assemble immutable, individually validated repair-stage checkpoints. These
checkpoints are generated by official_solid_exact_boundary_trial.py,
official_solid_regularize.py and the USB/contact continuation recipes;
their full provenance and SHA-256 are pinned in validated_components.json.
The failed tolerance-only assembly is never used as geometry input here.
"""
import json,hashlib
from pathlib import Path
from cadgen import step,build123d as bd,report

OUT=Path('V:/mouse/outputs/ZA13_OFFICIAL_PRECISION_REPAIR_03')

def digest(path):
    with open(path,'rb') as f:return hashlib.file_digest(f,'sha256').hexdigest()


@step(out='../outputs/ZA13_OFFICIAL_PRECISION_REPAIR_03/ZA13_DW_OFFICIAL_precision_solid.step')
def precision_solid():
    from official_solid_full_diagnose import load_input,shapes,bounds,INPUT
    from official_solid_compare_geometry import read
    from OCP.TopAbs import TopAbs_SOLID,TopAbs_FACE,TopAbs_SHELL
    from OCP.BRepCheck import BRepCheck_Analyzer
    from OCP.BRepGProp import BRepGProp
    from OCP.GProp import GProp_GProps
    from OCP.BRep import BRep_Tool

    manifest=json.loads((OUT/'validated_components.json').read_text())
    assert digest(INPUT)==manifest['reference_step_sha256']
    original=load_input();original_solids=shapes(original,TopAbs_SOLID)
    kept=[];record={'source_sha256':manifest['reference_step_sha256'],'solids':[],'original_bounds_mm':bounds(original),'removed_original_zero_volume_parts':[],'zero_volume_cleanup':manifest['zero_volume_cleanup']}
    def append(solid,label):
        prop=GProp_GProps();BRepGProp.VolumeProperties_s(solid,prop)
        volume=prop.Mass()
        if volume<0:solid.Reverse();volume=-volume
        assert volume>1e-12 and BRepCheck_Analyzer(solid).IsValid(),label
        assert all(BRep_Tool.IsClosed_s(s) for s in shapes(solid,TopAbs_SHELL)),label
        item=bd.Solid(solid);item.label=label;kept.append(item)
        record['solids'].append({'name':label,'faces':len(shapes(solid,TopAbs_FACE)),'volume_mm3':volume,'bounds_mm':bounds(solid)})
    def repaired_component(name):
        entry=manifest['components'][name]
        assert entry['valid'] and entry['self_intersections']==0,name
        path=Path(entry['brep']);assert digest(path)==entry['sha256'],name
        shape=read(path);solids=shapes(shape,TopAbs_SOLID)
        assert len(solids)==entry['solid_count'],name
        for j,solid in enumerate(solids):append(solid,name if len(solids)==1 else f'{name} {j+1}')
    report('Assemble validated solid geometry')
    for i,solid in enumerate(original_solids,1):
        label=f'Original part {i:03d}'
        prop=GProp_GProps();BRepGProp.VolumeProperties_s(solid,prop)
        if abs(prop.Mass())<=1e-12:
            record['removed_original_zero_volume_parts'].append(label);continue
        if i in (160,161):repaired_component(label)
        else:append(solid,label)
    for name in ('Side shell','Upper shell','Bottom shell','USB connector','Internal bracket'):repaired_component(name)
    result=bd.Compound(children=kept)
    record.update({'final_solids':len(kept),'final_faces':len(result.faces()),'final_bounds_mm':bounds(result.wrapped),'final_step_validation':'pending'})
    (OUT/'assembly_report.json').write_text(json.dumps(record,indent=2))
    return result


if __name__=='__main__':precision_solid()
