"""Materialize a tracked Python routing input after complete neutral path checks."""
import sys,json,pprint
from pathlib import Path
source=Path(__file__).resolve().parents[1]/'src'
sys.path.insert(0,str(source))
from lib.hand_routing import full_tendon_routes
from lib.path_analysis import path_length,path_min_radius
packet=json.loads(Path(__file__).with_name('wrist_transport_neutral.json').read_text())
assert len(packet['routes'])==48 and not packet['failures']
assert all(r['minimum_bend_radius_mm']>=3.5 and r['certified_prior_surface_gap_mm']>0 for r in packet['routes'])
routes=full_tendon_routes(packet['routes'])
for r in routes:
    r['length_mm']=float(path_length(r['path']))
    r['minimum_bend_radius_mm']=float(path_min_radius(r['path']))
    assert r['minimum_bend_radius_mm']>=3.5-1e-10
text='"""Neutral full paths; regenerated by validation/freeze_neutral_routes.py.\n\nCurve data is a tracked Python source input, never an untracked JSON read.\nThis freezes geometry for an integration study; acceptance gates remain separate.\n"""\nNEUTRAL_ROUTES = '+pprint.pformat(routes,width=120,sort_dicts=False)+'\n'
(source/'lib/neutral_routes.py').write_text(text)
print('froze',len(routes),'complete routed tendons',sum(r['length_mm'] for r in routes),'mm total')
