"""Read a model's generated animation module from beside it.

`@step(animation=...)` takes a JavaScript module as a Python string. For this
hand that module is SOLVED, not authored: `validation/write_showcase_presentation.py`
bakes 48 posed tendon routes, the payout and the body frames into megabytes of
JavaScript. Generated bytes that large are not source, so they are written to a
gitignored `<model>_animation.js` beside the model and read back here at build
time. The tracked model keeps the decisions; the sibling keeps the numbers.
"""

from pathlib import Path


def animation_path(model_file):
    """The generated sibling module for ``model_file``."""
    model = Path(model_file).resolve()
    return model.with_name(f"{model.stem}_animation.js")


def load_animation(model_file, generator):
    """Return the generated animation module, or say which command writes it."""
    path = animation_path(model_file)
    if not path.is_file():
        raise FileNotFoundError(
            f"{path} is missing. It is generated output, not source: run "
            f"`python validation/{generator}` from models/tendon_hand to write it."
        )
    text = path.read_text(encoding="utf-8")
    if "export const clips" not in text:
        raise ValueError(
            f"{path} exports no clips; regenerate it with "
            f"`python validation/{generator}`."
        )
    return text
